spring:
  datasource:
    url: jdbc:tc:postgresql:16-alpine:///resolvedesk?TC_REUSABLE=false
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

