spring:
  datasource:
    url: ${TEST_DB_URL:jdbc:tc:postgresql:16-alpine:///resolvedesk?TC_REUSABLE=false}
    username: ${TEST_DB_USERNAME:test}
    password: ${TEST_DB_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

